prometheus:
 prometheusSpec:
   storageSpec:
     volumeClaimTemplate:
       metadata:
         name: data
       spec:
         storageClassName: microk8s-hostpath
         accessModes: ["ReadWriteOnce"]
         resources:
           requests:
             storage: 5Gi

alertmanager:
 alertmanagerSpec:
   storage:
     volumeClaimTemplate:
       metadata:
         name: data
       spec:
         storageClassName: microk8s-hostpath
         accessModes: ["ReadWriteOnce"]
         resources:
           requests:
             storage: 5Gi

prometheus-node-exporter:
  hostRootFsMount:
    enabled: false